### ISSUE TITLE
Поле логин в базе данных. в ТЗ вроде не сказано, что будет логин. Нужно ли мне делать поле логин в форме регистрации?

### ISSUE THREAD

**Issue by tsyrya** [agarb7/my.briop#10]

**Comment by agarb7** [comment]
Когда до НГ собирались, предварительно решили, что пусть будет. Можно и убрать хотя.
Мне кажется оно будет полезно для маловероятного, хотя возможного, совпадения имени. Нужно ещё раз обсудить.

**Comment by svarkh** [comment]
Можно оставить и сделать как в личном кабинете my.bsu.ru - вход как по логину так и по ФИО
