### ISSUE TITLE
В вариативной части не добавляется тема к блоку тем

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#100]
Случайно наткнулся на баг.
![snapshot5](https://cloud.githubusercontent.com/assets/8955838/7280557/c3d34358-e94d-11e4-818a-7b80c6652e79.png)

**Comment by tsyrya** [comment]
Исправил, но я не стал из репов заливать, т.к. не знаю, что там у тебя сейчас релизовано, прямо в коде исправил. В репы залью изменения позже, сейчас какя-то ошибка с гитом, пока не разобрался

**Comment by agarb7** [comment]
я сейчас развернул из репа - и получается убил исправление 0_0

**Comment by tsyrya** [comment]
Я слил в репозиторий изменения, залей пожалуйста.

**Comment by agarb7** [comment]
залил
