### ISSUE TITLE
Не загружаются файлы для УМК

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#101]
Я пробовал скрипт деплоя проекта написать, и видимо папку для файлов пользователя не учёл. Как она называлась?

**Comment by tsyrya** [comment]
/web/data
Может яперепишу код, чтобы он сам создавал папку в случае, если ее нет?

**Comment by agarb7** [comment]
Йии не создаёт свои рабочие папки (рантайм, веб/ассетс), и выводит ошибки если их нет. Не могу сказать наверняка почему он так делает, но наверное нам тоже не нужно)))

**Comment by agarb7** [comment]
Добавил эту папку в реп, но наверное потом уберу и перенесу в скрипт деплоя
