### ISSUE TITLE
Программа курса. ПК

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#102]
В ДПП ПК
1.: в пояснительной записке
1.1.Заменить Технические условия на Материально-технические условия
1.2.Добавить окно Итоговая аттестация после  Материально-технические условия

2.: В содержании
2.1. при добавлении темы заменить Вид работ на Вид занятий
2.2. при добавлении темы в окне Преподаватель возможность внести приглашенного, добавить Вакансия. Для этого внести сотрудник "Вакансия"
2.3. заменить Список литературы на Литература
2.4. в теме добавить окно Неделя

**Comment by tsyrya** [comment]
все сделал кроме вакансий. Прошу Сашу просто добавить физлицо "Вакансия" и внести ее на каждую кафедру

**Comment by agarb7** [comment]
Извините, но не могу себе позволить вставить такой костыль. Вместо этого я добавил возможность полю "преподаватель" сущности "тема курса" принимать значение "вакантно". Мне понятна мотивация сделать отдельный объект физ.лица со значением "Вакансия". Но это ошибочный ход, - костыль, - который обязательно приведёт к проблемам в будущем.

## Доказательство "костыльности" ))):

Это костыль, потому что Физ.лицо - это физический человек, а физический человек не может быть абстрактным понятием "вакансия". Т.о. сущность используется не по назначение, что и есть костыль по определению.

## Возможные последствия, которые я смог вообразить

1. Возможно придётся фильтровать всевозможные списки физ.лиц чтобы в каком-нибудь месте системы в этот список не влезло физ.лицо вакансия. (Статистику по физ.лицам тоже придётся избавлять от назойливого гражданина "Вакансия".)
1. "Вакансия" должен иметь хорошо известный айдишник (нужно отметить что id=1 уже давно занят), его наверное нужно будет хранить в отдельной конфигурационной таблице и заботится о его соответствии при миграциях. Такое хранение и эволюция конечно вполне естественно, но намекают на то что ввод костыля отнюдь не такое дешёвое занятие как кажется в начале. 

## Другие последствия
Вероятны и другие неудобства, которые возникнут из-за того что объекты используются не по назначению, и проявляются в областях где не должны проявляться.

## Почему хочется сделать воткнуть именно такой костыль
Мотивация действительно правильная и я её разделяю. Но не разделяю способ реализации. Мотивация же кроется в следующем: дать возможность принимать полю "преподаватель" дополнительное значение "вакантно". Самый быстрый (и неверный) способ это сделать нам уже известен. Концепция SQL слишком топорно чтобы выражать такую логику, поэтому решение не очень красивое, но вполне  удовлетворяющая требованиям согласованности данных. 
Итак нужно, чтобы: преподаватель = <нет доп. информации | определённый преподаватель | место вакантно>.
Чтобы не терять контроля по внешнему ключу - нельзя делать поле композитным типом. Поэтому я оставил это поле переименовав его в prepodavatel_fiz_lico, и добавил ещё одно поле prepodavatel_vakansiya для хранения доп. значения "вакансия". Логически это одно поле prepodavatel, но физически (из-за ограничений языка SQL) их два.
Теперь осталось добавить ограничения, чтобы гарантировать правильное совместное хранение этих физических полей.
Принцип совместного хранения описан в таблице:

prepodavatel_vakansiya | prepodavatel_fiz_lico | смысл
------------------------------- | --------------------------- | --------
N | N | нет доп. информации 
N | fiz_lico.id | определённый преподаватель
f | N | не имеет смысла
f | fiz_lico.id | не имеет смысла
t | N | место вакантно
t | fiz_lico.id | не имеет смысла

N - null, t - true, f - false
