### ISSUE TITLE
Программа курса. ДПП ПП, ПО

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#103]
В ДПП ПП, ПО

В пояснительной записке после Материально-технические условия
1 добавляем окна:
1.1.Характеристика нового вида профессиональной деятельности, новой квалификации
1.2. Требования к уровню подготовки
1.3. Форма обучения
1.4. Режим занятий

2.: в содержании
2.1. В действиях дисциплины убрать Добавить УМК
2.2. В действиях темы убрать Добавить УМК
2.3. Заменить в КИМ Форма контроля подраздела на Форма контроля дисциплины
2.4. Заменить Контроль по подразделу  на Контроль по дисциплине - в КУГе, УП
2.5. В действиях КИМ убрать Добавить КИМ
2.6. При  добавлении темы убрать окно Аннотация
2.7. В действиях КИМ итоговой аттестации убрать Добавить тему итоговой работы
2.8. Удалить список литературы
2.9. При добавлении дисциплины добавить выбор из списка "руководитель дисциплины". В дальнейшем это новая роль личного кабинета.  "руководитель дисциплины" получит права на составление РПД куда войдут убранные пункты - инструкций по РПД пока нет.

**Comment by tsyrya** [comment]
2.5. В действиях КИМ убрать Добавить КИМ - это вообще не понятно что такое.
Остальное сделал
