### ISSUE TITLE
Переделать генерацию на yii2-mpdf и удалить рукотворный mpdf

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#117]

**Comment by tsyrya** [comment]
При чистке index-файла у меня возникли проблемы с генерацией pdf. Пока ты не переделал, я в коде require сделал, прямо в том контроллере. Нужно было срочно протестить код, не было времени разбираться с тем, как сделать это на yiiшном mpdf, поэтому пока так сделал

**Comment by agarb7** [comment]
Сделал
