### ISSUE TITLE
Проблемы с регистрацией

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#118]
![reg-err](https://cloud.githubusercontent.com/assets/8955838/7776141/dec4a790-00e2-11e5-9659-d688c911545b.png)

**Comment by agarb7** [comment]
Изменил `telephonnyj_nomer character varying(16)` на `telephonnyj_nomer character varying(255)`. Проблема должна решиться. Но это было далеко не лучшее решение.

**Comment by tsyrya** [comment]
Да зачем. Я там добавил подсказку, как вводить.и снодня в коде внёс проверку на количество символов

**Comment by tsyrya** [comment]
Веесу)

**Comment by tsyrya** [comment]
*внесу

**Comment by agarb7** [comment]
Без ишью было непонятно.

Можно ещё обработку ввода в код:
```php
function onlyDigits($str)
{
        return mb_ereg_replace('\D', '', $str);
}
```
