### ISSUE TITLE
Нужно ли явно в репозиторий добавить SQL-файлы для КЛАДРа или достаточно скрипта конвертации?

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#12]
Сейчас есть скрипт конвертации, который запускает утилиту **pgdbf** для конвертации DBF в SQL. Ему нужны два файла из официального КЛАДРа: KLADR.DBF и STREET.DBF; которые нужно положить в /data_res/kladr/.  Если залить файлы явно то они сразу дико утяжелят репозиторий на ~90 MiB. И будут утяжелять на такое же количество при каждом обновлении КЛАДРа по ходу разработки в этом репозитории. 
Я было хотел залить, но передумал. Как думаете?

**Comment by tsyrya** [comment]
Думаю нет, размер большой получается
