### ISSUE TITLE
Ошибка в списках зарег. на курсы на next.briop

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#120]
Например, Тармаева Елена Раднаевна.
![snapshot8](https://cloud.githubusercontent.com/assets/8955838/7793686/743aa09e-02ec-11e5-90b9-0bddef1ea06d.png)
Похоже на ошибку в запросе.

**Comment by tsyrya** [comment]
SELECT * FROM kurs WHERE rukovoditel=%d
вот такой запрос, предельно простой=)

**Comment by agarb7** [comment]
Да))) В mybriop те же данные. И, по всей видимости, так и должно быть.
![snapshot9](https://cloud.githubusercontent.com/assets/8955838/7796557/a5b5fb0a-030a-11e5-9686-17f125db03b4.png)
Либо сообщение об ошибке ложное, либо нуждается в более конкретной формулировке.

**Comment by tsyrya** [comment]
Есть ещё одна проблема, которую я не замечал раньше. Например, курс с айди 46 названия в базах отличаются и, видимо, список не тот. Я, как я думаю, в этом была проблема. Мы не туда копали)

**Comment by agarb7** [comment]
Нет, одинаковые:
```
agarb@storm:~$ psql -Umybriop -hlocalhost
Пароль пользователя mybriop: 
psql (9.4.0, сервер 9.4.1)
SSL-соединение (протокол: TLSv1.2, шифр: ECDHE-RSA-AES256-GCM-SHA384, бит: 256, сжатие: вкл.)
Введите "help", чтобы получить справку.

mybriop=> select id,nazvanie from programma_obucheniya where id=46;
 id |                                             nazvanie                                              
----+---------------------------------------------------------------------------------------------------
 46 | Реализация системно-деятельностного подхода на уроках химии в соответствии с требованиями ФГОС ОО
(1 строка)

mybriop=> \q
agarb@storm:~$ psql -Unextbriop -hlocalhost
Пароль пользователя nextbriop: 
psql (9.4.0, сервер 9.4.1)
SSL-соединение (протокол: TLSv1.2, шифр: ECDHE-RSA-AES256-GCM-SHA384, бит: 256, сжатие: вкл.)
Введите "help", чтобы получить справку.

nextbriop=> select id,nazvanie from kurs where id=46;
 id |                                             nazvanie                                              
----+---------------------------------------------------------------------------------------------------
 46 | Реализация системно-деятельностного подхода на уроках химии в соответствии с требованиями ФГОС ОО
(1 строка)
```

**Comment by tsyrya** [comment]
Извиняюсь, у меня в коде косяк был. Но тогда я не понимаю, в чем ошибка=)

**Comment by tsyrya** [comment]
Я думаю вопрос закрыт. Видимо вопрос как раз в том и был, что название в самом списке было неверным
