### ISSUE TITLE
Стажи физ. лица. Не слишком ли их много?

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#146]
У нас сейчас есть:

1. Общий пед. стаж
1. Стаж на конкретном должности в конкретной организации
1. Общий стаж в должности безотносительно организации

Нам точно нужны они все?

**Comment by svarkh** [comment]
да это было отмечено в ТЗ

**Comment by agarb7** [comment]
Ок. Уточнил на всякий случай. Т.к. для пользователя это несколько обескураживающе.

**Comment by svarkh** [comment]
1. это вполне общее понятие
2. и 3. выглядит действительно странно, но это заказчик определил как нечно тавное для отчетов
