### ISSUE TITLE
Замечания по тестированию регистрации на курсы

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#15]
1. Регистрация
Группа Место работы. Дополнительная фильтрация.
выбрать район затем из списка образовательных учреждений района выбрать нужное учреждение при этом оставить возможность впечатать название школы сразу
2. Курсы. Подробнее
в поле форма обучение
вместо "заочно" прописать "заочно (электронное обучение)" 
3. Курсы очно-заочно
"Достижение личностных, метапредметных и предметных результатов образования по предметам естественнонаучного цикла" нет сроков
очно с по
заочно с по
данные подавались со сроками
4. Срок обучения проставить с годом

**Comment by svarkh** [comment]
Появились замечания
1. Вынести форму обучения в отдельное поле после Записано
2. Нет возможности редактирования курсов без дат. Сейчас требует ввести дату.

**Comment by tsyrya** [comment]
Сделал
