### ISSUE TITLE
Организовать в бд возможность добавления вакансии в контролирующих по курсу

### ISSUE THREAD

**Issue by tsyrya** [agarb7/my.briop#150]

**Comment by agarb7** [comment]
по аналогии с #102

**Comment by tsyrya** [comment]
Ага, тогда миграцию сделаешь?

**Comment by agarb7** [comment]
@tsyrya да

**Comment by agarb7** [comment]
Таблицу контролирующий по курсу сделаю сущностью (сейчас просто таблица связка): переименую в "контролирующий_курса" и добавлю id, далее добавлю булево поле "контролирующий_вакансия" тогда вакансия имела бы смысл аналогичный вакансии препода.
