### ISSUE TITLE
Ограничение на возможные объёмы курса

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#21]
Насколько строго ограничение:
"9.1.3.5.3. Количество часов – справочник/{16, 24, 28, 32, 40, 72, 108}"
?
В план-проспекте есть ещё такие: 250, 304, 404, 502, 526, 600, 610, 659, 660, 664.

**Comment by agarb7** [comment]
В план-проспекте есть ещё такие:
250
304
404
502
526
600
610
659
660
664

**Comment by svarkh** [comment]
Нужно дополнить справочник всеми вариантами часов т.е.
{16, 24, 28, 32, 40, 72, 108, 250, 304, 404, 502, 526, 600, 610, 659, 660, 664}

**Comment by agarb7** [comment]
Этот справочник носит рекомендательный харктер или можно создавать курсы только строго с часами из этого списка? (Сейчас это ограничение строгое)

Сейчас полный список возможных часов собранный из плана-проспекта:
{6, 8, 16, 24, 32, 36, 40, 48, 56, 72, 250, 304, 404, 502, 526, 600, 610, 659, 660, 664, 672}.
