### ISSUE TITLE
Кратность часов темы курса

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#22]
Тема курса фиксирована по продолжительности 2 часа. Может быть для использования  удобнее фиксировать только кратность 2 часам.

**Comment by svarkh** [comment]
Тема должна быть только 2 часа т.к. из содержания будет создаваться расписание

**Comment by svarkh** [comment]
Вопрос снова открыт. Во вторник точно скажут насчет кратности похоже, что у нас появятся часы кратные двум.

**Comment by agarb7** [comment]
Если да, то в таблицу "тема", добавлю поле "часы".

**Comment by agarb7** [comment]
Разговор перехал в #44
