### ISSUE TITLE
 Определение ведомства к которому относится обр. организация 

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#24]
Сейчас все обр. орг. в базе забиты как относящиеся к МИНОБРу, что, возможно, неправильно.

Можно ли это сделать автоматически исходя из названия или попросить сотрудников БРИОПа сделать это вручную?

Я думаю мне стоит выкатить список обр.орг. в электронную таблицу и проанализировать её совместно с сотрудником БРИОПа, чтобы найти закономерности для полуавтоматической конвертации, а что нельзя автоматом они проставят руками.

**Comment by svarkh** [comment]
Сегодня решили, что это для нас не существенно. Фильтр на объем часов работает по привязке уровня к физлицу

**Comment by agarb7** [comment]
Тогда как определять, кто проходит бесплатно (потому что относится Минобрнауки), а кто платно (потому что относится к другому ведомству)?

**Comment by agarb7** [comment]
Сейчас в БД все Минобрнауки (как сказали в БРИОП).
