### ISSUE TITLE
Определение этапа образования к которому относится обр. организации

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#25]
Сейчас все обр. орг. в базе забиты как относящиеся к среднему общему образованию, что неправильно.

Можно ли это сделать автоматически исходя из названия или попросить сотрудников БРИОПа сделать это вручную?

Я думаю мне стоит выкатить список обр.орг. в электронную таблицу и проанализировать её совместно с сотрудником БРИОПа, чтобы найти закономерности для полуавтоматической конвертации, а что нельзя автоматом они проставят руками.

**Comment by svarkh** [comment]
Пока это не актуально т.к. функции фильтрации работают и без этого

**Comment by agarb7** [comment]
полка закрываю
