### ISSUE TITLE
Замечания по тестированию регистрации на курсы

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#37]
1. Нужно продублировать фильтр для функционала редактирования план-проспекта!!!
2. При добавлении внебюджетного курса в план-проспект поля дата и число слушателей - могут быть пустыми. Сейчас фактически внебюджет без дат и сроков  добавить нельзя.
3. Нужно дать право добавления подразделений в справочник. Вопрос возник в связи редактированием плана-проспекта - забыли вписать "ЛАБОРАТОРИЯ ЭТНОКУЛЬТУРНОГО ОБРАЗОВАНИЯ" и как следствие не могут отредактировать.
4. При добавлении курса поле описание тоже может быть пустым т.к. к отдельным курсам его просто нет

**Comment by agarb7** [comment]
Пункт 3.
Сейчас в БД на сервере такие структурные подразделения:
1 | кафедра экономики, права и государственного управления
  2 | кафедра инновационного проектирования
  3 | кафедра развития образовательных систем
  4 | центр методического сопровождения педагогических работников и образовательных организаций
  5 | центр развития профессионального образования
  6 | лаборатория развивающего образования
  7 | учебный отдел
Как я понял: лаборатория развивающего образования == лаборатория этнокультурного образования. Просто это опечатка в первых версия присланных БРИОПом данных. Потом они исправили, но заливать исправленные данные было поздно, т.к. БД уже редактировалась сотрудниками. 
Поэтому предлагаю сделать так:  сейчас просто исправим опечатку и не реализовывать функционал правки, чтобы сэкономит время. Т.к., я думаю, справочник стуктурных подразделений, если изменится, то только на следующий год.

**Comment by svarkh** [comment]
Согласен
