### ISSUE TITLE
Добавить в таблицы umk_temy и kim_temy поле id

### ISSUE THREAD

**Issue by tsyrya** [agarb7/my.briop#38]
Вообще давай заведем правило, во всех таблицах должно быть поле id

**Comment by agarb7** [comment]
Даже в те таблицы которые просто реализуют связь n:m?

**Comment by tsyrya** [comment]
Да

**Comment by agarb7** [comment]
Добавил id.
Пока, кроме m:n - в них комбинированный пк - пара айдишников двух таблиц. Не стал менять пока это.
Правило нужно чтобы унифицировать порцедуры работы с сущностями?
