### ISSUE TITLE
Уточнение по программе курса. Одно название темы для лекции и практики.

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#39]
В программе курса должна быть возможность сохранения одного названия темы для разных видов занятий. Например лекция "Преобразование Лапласа" - 2 часа и практика "Преобразование Лапласа" - 2 часа.
Если же возникла ситуация назначения 2 к 4, то будет так
лекция "Преобразование Лапласа" - 2 часа
практика "Преобразование Лапласа (часть 1)" - 2 часа
практика "Преобразование Лапласа (часть 2)" - 2 часа
Изначально мы обсуждали, что все названия будут отличаться. Но в случае лекции и практики с одинаковым числом часов будет выглядеть странно.

**Comment by agarb7** [comment]
В БД нет ограничения на уникальность темы.
