### ISSUE TITLE
Можно ли где-нибудь найти список образовательных учреждений?

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#4]
Нужно заполнить справочник. Список, желательно, сразу с адресом (или районом, где оно находится), ведомством и уровнем (этапом) образования (которое оно предлагает) .

**Comment by tsyrya** [comment]
Он вроде у них есть, скоро предоставят

**Comment by svarkh** [comment]
Завтра скину ссылку с официального источника на перечень организаций

**Comment by svarkh** [comment]
как оказалось это список - реестр выданных и отнятых лицензий. Я попросил учебный отдел подготовить для нас файл xls с двумя колонками район и наименование учреждения. Привязка к району нам нужна для формирования отчетов. Пока ждем

**Comment by agarb7** [comment]
Файл был подготовлен. Но на данный момент не окончательный.
