### ISSUE TITLE
Уточнение ТЗ. Курсы ПП и ПО подразделы дисциплин

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#40]
В курсах ПП и ПО есть дисциплины до 120 часов. Поэтому в содержании курса для дисциплины с большим числом часов пользователь должен иметь возможность добавить подраздел, а в подразделе тему. При этом сохранить  возможность добавлять тему к дисциплине непосредственно.

**Comment by agarb7** [comment]
Физически в БД тему непосредственно к дисциплине добавить нельзя, только в подраздел, а подраздел добавляется непосредственно к курсу. 
Как сейчас добавляется тема непосредственно к дисциплине? Через промежуточную "служебную псевдо-тему"? Как непосредственное добавление темы к дисциплине соотносится с разделами (раздел 1,2,3; вариативная часть)?
Нужно ли отразить в БД возможность непосредственного прикрепления темы к курсу?

**Comment by agarb7** [comment]
Структурно дисциплина = блок тем. "Подраздел" - их обобщённое название из ТЗ.
Дальнейшее деление подразделов на подразделы нами делаться не будет, как я понял.
Вместо этого будем делать большие часы ( #44  ) для тем.
Закройте это issue если с этим всё.

**Comment by svarkh** [comment]
Совершенно верно. В ТЗ сказано
10.1.3.6.1.1.1. Добавить «подраздел»: 
10.1.3.6.1.1.1.1. Наименование блока тем - в курсах повышения квалификации)
10.1.3.6.1.1.1.2. Наименование дисциплины - в курсах профессиональной переподготовки, профессионального обучения
