### ISSUE TITLE
Программа курса. Тема. Замена Аннотации на Содержание.

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#41]
Нужно заменить слово Аннотация на Содержание  при формировании темы.

**Comment by agarb7** [comment]
Можно тогда я в БД в таблице "tema" переименую поле "annotaciya" в "soderzhanie", для лучшего отражения предметной области?

**Comment by agarb7** [comment]
переименовал))

**Comment by svarkh** [comment]
Это правильно главное чтобы Цырен это сделал тоже!
