### ISSUE TITLE
Загрузка перечня примерных тем дипломных работ при формировании курса

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#43]
В ТЗ сказано:
"10.1.3.6.4.1.1. Если выбран элемент из списка {выпускная аттестационная работа,
выпускной квалификационный экзамен}, то предоставить форму для загрузки перечня
примерных тем дипломных работ."
Сейчас в БД устроено так, что этот список разбит по названиям тем. Т.е. на каждую тему - отдельная запись. 
Альтернативный вариант организации - все темы залить в одну запись. Т.е. курсу соответствует одно текстовое поле со списком всех тем, либо файл-документ (по аналогии с КИМ и УМК). 

Плюсы первого варианта:
1. Можно (если вдруг потом понадобиться) легко узнавать сколько тем для итоговых работ у этого курса. И, допустим, сообщать создателю если их не достаточно много (не хватает на всех слушателей), или показывать, что в среднем на студента x тем итоговых работ.
2. Можно (если вдруг потом понадобиться)  устанавливать соответствие между темой итоговой работы и конкретным слушателем курса.
3. Позволит при распечатке программы курса, включать в него примерные темы аттестационных работ унифицированным отформатрованным списком.
4. Становится возможным (если вдруг потом понадобиться) более удобный поиск/фильтр по темам итоговых работ.
Минусы:
1. Пользователю муторно вбивать каждую тему.

Плюсы второго варианта:
1. На него намекает ТЗ.
2. Несколько проще реализуется, чем первый вариант.
3. Пользователю легче заполнить курс - залить всё скопом.
Минусы:
1. Если темы были одним файлом, - нужно скачивать этот файл, чтобы просто посмотреть список тем.
2. Слабый контроль над содержимым файла/поля, потенциально увеличивает возможные ошибки пользователя.

**Comment by svarkh** [comment]
Озадачил УО БРИОП. Ждем ответа

**Comment by agarb7** [comment]
Скорее всего понадобиться возможность загрузки КИМа к итоговой аттестации (#48), в независимости от того войдут ли в него темы дипломных работ или нет.

**Comment by svarkh** [comment]
Тут делема! В дальнейшем тема пойдет в диплом. Поэтому запись вроде как нужна отдельная на каждую тему. Но будет и приказ о назначении тем дипломных работ, причем сами темы могут быть изменены на кануне приказа. Таким образом, основным документом из которого будем дергать темы может быть и приказ, а если так, то смысл создавать проблему точного списка тем на этапе программы. Ваше мнение?

**Comment by agarb7** [comment]
Структурированная информация - это хорошо. Например, если приказ тоже формируется и хранится в нашей системе, то можно автоматически вносить в него темы из программы, естественно с возможностью их правки. Ещё мне кажется плюс (3) из списка тоже важен. 
Но, может быть, тогда нужно для выдерживания общей линии проекта вопросы на экзамен/зачёт тоже сделать списком. И вообще подумать над унификацией КИМов. Хотя это можно оставить на дальнейшее развитие системы и бизнес процессов БРИОПа.
Тут моё дальнейшее рассуждение зависит от того нужна ли вообще в бизнес-логике нашего проекта в том или ином качестве отдельная запись или сущность "тема дипломной работы" (например для печати на бланке диплома). Нужна ли она?

**Comment by svarkh** [comment]
Тогда заводим по одной и считаем, что в приказ информация о темах пойдет из программы.
Что касается списка вопросов к экзамену, то здесь  однозначно списком т.е. загружаем в текстовое поле список вопросов.

**Comment by agarb7** [comment]
Т.е. вопросы будут добавляться plain текстом через вэб-форму, но не файлом?

**Comment by svarkh** [comment]
сделаем два варианта будет удобно для смартфонов, планшетов
