### ISSUE TITLE
Курсы ПП и ПО. Темы дисциплин кратно 2.

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#44]
Необходимо добавить возможность выбора часов к теме кратно 2.
Этот функционал должен быть только в курсах ПП и ПО, т.е. в курсах ПК темы должны быть только по 2 часа.

**Comment by svarkh** [comment]
Ранее (не на страницах github) обсуждалось добавление подразделов к дисциплинам. Этот вопрос закрыт.

**Comment by agarb7** [comment]
Структурно дисциплина = блок тем. "Подраздел" - их обобщённое название из ТЗ. 
Дальнейшее деление подразделов на подразделы нами делаться не будет, как я понял.
Добавлю поле "часы" в "тему курса".

**Comment by agarb7** [comment]
Добавил поле "часы" в "тему курса".
