### ISSUE TITLE
Программа курса. Отображение Содержания

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#47]
В Содержании программ курсов просят отображать нумерацию как в КУГе

**Comment by agarb7** [comment]
Сейчас порядок тем и блоков обусловлен id этих сущностей в БД. Это не совсем правильно, т.к. суть и назначение id - идентифицировать, а не упорядочивать. Например, становиться очень затруднительно перемещать темы. (Хотя такой функционал пока как я понимаю, не требуется)
Я думаю нужно непосредственно отразить отношение порядка тем и блоков в БД. 
Один из вариантов - это явно хранить номер темы/блоке в столбце nomer (например). Он и будет отображаться в таблице.
Так и сделать?

**Comment by agarb7** [comment]
Добавил номер в соответствующие таблицы БД.

**Comment by svarkh** [comment]
Мне казалось что в базе это не обязательно. Главное чтоб отражалось на форме у клиента.

**Comment by agarb7** [comment]
Нужно только для строгой определённости порядка. И чтобы избавить id от несвойственной ему ответственности.

**Comment by svarkh** [comment]
Честно говоря я не планировал, что понадобится функционал перетаскивания тем по порядку хотя теперь мне кажется это понадобится. Пока тему не закрываем возможно придется вернутся если нас об этом попросят.
