### ISSUE TITLE
Программа курса. Контроль.

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#48]
по тз формы контроля вяжутся к темам и не имеют выделенных часов. т.е. контроль в теме не влияет на часы. Это так и сохранится.
Нужно добавить функционал добавления контроля к  дисциплине / блоку тем при этом дать возможность выбрать часы кратные 2. Эти часы будут учитываться в КУГ и Учебном плане.

**Comment by agarb7** [comment]
Есть итоговая аттестация:
"10.1.3.6.4. Итоговая аттестация
10.1.3.6.4.1. Формы итоговой аттестации – справочник {экзамен, зачет, защита проекта,
выпускная аттестационная работа, итоговый комплексный экзамен, выпускной
квалификационный экзамен}
10.1.3.6.4.1.1. Если выбран элемент из списка {выпускная аттестационная работа,
выпускной квалификационный экзамен}, то предоставить форму для загрузки перечня
примерных тем дипломных работ.
10.1.3.6.4.2. Количество часов итоговой аттестации"

Есть контроль к теме:
"10.1.3.6.1.1.7. Возможные действия для созданных тем
10.1.3.6.1.1.7.1. Добавить форму контроля к сохраненной теме – справочник {экзамен,
зачет, тест, контрольная работа, защита проекта}
10.1.3.6.1.1.7.1.1. Если выбран элемент из списка {экзамен, зачет, тест, контрольная
работа, защита проекта}, то предоставить форму для загрузки файла или ссылки на
электронный ресурс КИМа."

Пока нет возможности добавления контроля к блоку тем (подразделу). Будет ли он аналогичен итоговой аттестации, либо это принципиально другая форма контроля?

**Comment by agarb7** [comment]
Какой справочник использовать для контроля в подразделах (блоках тем/дисциплинах):
1) собственный для подразделов (взять у УО);
2) справочник итоговой аттестации (ТЗ 10.1.3.6.4.1);
3) справочник форм контроля темы (ТЗ 10.1.3.6.1.1.7.1) ?

Если имеется контроль на всех уровнях программы курса (итоговый, на уровне подраздела и темы), то тогда нужно добавить возможность загрузки КИМов на все уровни. Так ли это?

**Comment by agarb7** [comment]
Для контроля в подразделах используется справочник форм контроля темы. И нужно добавить загрузку кимов на все уровни.

**Comment by agarb7** [comment]
Добавил в БД.
