### ISSUE TITLE
Подгрузка УМК для всех уровней программы курса

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#49]
По аналогии с КИМами на всех уровнях (#48), наверное будет правильно прикреплять УМК ко всем уровням.
Например, УМК может относиться сразу к блоку тем, а не к конкретной теме из этого блока, тогда его правильнее подгрузить непосредственно к блоку тем, что, в прочем, не отменяет возможности догрузить специфичный теме УМК непосредственно к теме внутри блока. Аналогично с УМК для курса в целом.

**Comment by svarkh** [comment]
С этим согласились и в учебном отделе. Единственное, что можно этот момент отложить и сделать чуть позже. Хотя все зависит от времени Цырена.

**Comment by agarb7** [comment]
Добавил возможность в БД
