### ISSUE TITLE
Найти справочник кодов подразделений паспортных столов

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#5]
Это нужно? Это возможно?

**Comment by svarkh** [comment]
Это нужно и это сделает Цырен у нас уже есть подобная штука в Университете

**Comment by tsyrya** [comment]
Сегодня на почту дамп потравлю, там только не у всех есть наименования

**Comment by tsyrya** [comment]
но коды вроде все есть

**Comment by tsyrya** [comment]
Отправил на почту. Дошли данные?

**Comment by agarb7** [comment]
Да, дошли. Только не знаю лить их или нет :-/ Может оставть на совесть пользователей?
Т.к., судя по всему, это тоже собранные от пользователей данные, со всеми вытекающими. 
Например:
("000000","Денизли"),
("000024","Абр")
("000085","")
("000089","")
("000496","")
("002003","ОВД")
("030 - ","Отделением УФМС России по РБ в Заиграевском р - не")
("030-00","ТП в пос. Заречный ОУФМС России по Республике Бурятия в Советском районе гор. Улан-Удэ")
("030006","0")
("030-01","отделением УФМС России по республике Бурятия в Заиграевском районе")
("031-12","asdsasa")
("032-","ТП УФМС РФ по РБ Киж. районе")
("032-00","ОВД Октябрьского р-а г.Улан-Удэ Республики Бурятия")
("032000","ОВД октябрьского р-на г.Улан-Удэ")
("032001","0")
("003-00","отделом уфмс по рб г.улан-удэ")

**Comment by tsyrya** [comment]
Да, данные вносили пользователи. Нужно так же обсудить, наверное, может можно обратиться в УФМС, может они смогут базой педелиться

**Comment by agarb7** [comment]
Я закрою тему, т.к. решили что, по крайней мере пока, подразделение вводится руками пользователя.
