### ISSUE TITLE
Программа курса. Контроль блоков тем/дисциплин - учет часов. 

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#55]
При пересчете часов УП и КУГ необходимо учитывать часы контроля привязанного к блокам тем/дисциплинам. Сейчас этот работает только для КУГ.

**Comment by svarkh** [comment]
К вопросу о распределении  нагрузки. Возможны случаи когда экзамен принимают несколько человек и всем им падает нагрузка по экзамену. Более того, возможно, что некоторые из них не читали ни одну тему по данному блоку тем или дисциплине. Решение: в форму контроля к дисциплине или блоку тем добавить инструмент добавления списка экзаменаторов из числа преподавателей БРИОП.

**Comment by agarb7** [comment]
Форма контроля к дисциплине и блок тем - это одно и тоже понятие в смысле структуры программы курса. Добавил возможность в БД прикриплять контролирующих преподавателей как к дисциплине (блоку тем), так и к курсу.
