### ISSUE TITLE
Список педагогов БРИОП

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#57]
список сотрудников в справочнике программы курса не полный. Возможно отбирали только из числа кафедр. Здесь читают все начиная с ректора. Если причина в недогрузке дополнить. В последнем файле не хватало только нового проректора по науке. Файл скину позже через почту. Кстати я скидывал свой аккаунт google...

**Comment by agarb7** [comment]
Залиты все кроме (пока) нового проректора.
Возможно стоит фильтрация по типу должности.

Тип должности:
- должность педагогического работника, отнесенная к профессорско-преподавательскому составу;
- должность педагогического работника, не отнесенная к профессорско-преподавательскому составу;
- должность руководителя;
- должность заместителя руководителя, руководителя структурного подразделения и его заместителя, иная должность руководителя.
Первые две - должности педагогических работников организаций, осуществляющих образовательную деятельность.
Следующие - должности руководителей образовательных организаций.

Сейчас должности может соответствовать тоько один тип. Может быть пересмотреть это и сами типы?

**Comment by svarkh** [comment]
В этой организации очень странные понятия нагрузки. Так ректор читая часы не прикреплен к кафедре! Поэтому в этом списке нужно показать всех.

**Comment by agarb7** [comment]
По какому принципу сейчас работает фильтрация?

**Comment by svarkh** [comment]
Думаю на самом деле лучше чтоб они добавили нужных сотрудников к кафедрам.
В этом случае у нас не будет проблем с предоставлением информации тому же ректору как сотруднику кафедры т.е. его нагрузку расписание и т.д. Поэтому этот вопрос я решу административным путем.
