### ISSUE TITLE
В базах nextBriop и myBriop добавить поле предела слушателей на курс

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#64]
Я правильно понял?

**Comment by tsyrya** [comment]
Вроде как да.

**Comment by agarb7** [comment]
Добавил и там и там: maksimalno_slushatelej integer.

**Comment by tsyrya** [comment]
что-то в репозитории не вижу

**Comment by agarb7** [comment]
В myBriop - сразу на сервере сделал. т.к. теперь из репозитория его не зальёшь, а синхронить и там и там изменения - весьма сложно.
Попробую сделать дамп без лишних данных - и скину на мыло.

**Comment by tsyrya** [comment]
А там проставили количество равное количеству в поле расчитано слушателей?

**Comment by tsyrya** [comment]
Дамп не нужо руками в бд добавлю

**Comment by agarb7** [comment]
Ок. Пока просто помним, что sql в ветке master не актуальны, в том смысле, что схема в репе не соответствуют рабочей схеме на сервер.
Позже, возможно, либо удалю, либо актуализирую схему.
