### ISSUE TITLE
Ограничение в БД на логин.

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#65]
Опишите множество допустимых логингов, а я реализую его физическим ограничением в mybriop и nextbriop.
Те логины в mybriop которые не попадут в это множество, наверное, нужно будет удалить.

**Comment by agarb7** [comment]
mybriop=> select * from polzovatel where id in (129, 132);
 id  |   login   | fiz_lico | parol_md5 | podtverzhden 
-----+-----------+----------+-----------+--------------
 129 | irjkf2015 |      357 |    ----    | t
 132 | Irjkf2015 |      360 |    ----    | t

Отличаются только заглавной первой буквой - удалил 129-го.

**Comment by tsyrya** [comment]
Ограничения тоже, только можно цифрыписать, я бы так написал [a-z0-9]*{1,20}

**Comment by agarb7** [comment]
Согласен, пусть так и будет. - Имеется ввиду регистронезависимый логин.

**Comment by agarb7** [comment]
Пользователи уже в БД понаписали заглавных. Я пока добавил ограничение которое не даёт записать логин в БД если он отличается тоько регистром и ограничение на домен из твоего кода: ^[a-zA-Z0-9]{1,20}$
Но переделаю на ^[a-z0-9]{1,20}$ и приведу всех к строчным буквам, когда ты реализуешь регистронезависимую проверку логина. 
Кстати мне тоже её надо реализовать в yii2-version))

**Comment by agarb7** [comment]
Переназначь это ишью мне, когда реализуешь. И я БД причешу (приведу всех к строчным и поставлю ограничение).

**Comment by tsyrya** [comment]
реализовал регистронезависимость

**Comment by agarb7** [comment]
причесал БД
