### ISSUE TITLE
Другие разделы или имена разделов

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#66]
Упоминалось, что имеются программы курсов с именами разделов отличающимися от жестко указанных в ТЗ. Например, "Р.1. Нормативно-правовые основы образовательной деятельности" может носить другое наименование. Или же вообще отличаться деление на разделы и деление на базовую и вариативную часть.
Это остаётся жёстко в соответствии с ТЗ или нужно предусмотреть такую возможность сейчас или в ближайшем будущем?

**Comment by svarkh** [comment]
Тема перешла в https://github.com/agarb7/my.briop/issues/89
