### ISSUE TITLE
Виджет статуса и управления аутентификацией

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#67]
Виджет, который показывает логин (возможно роли), ФИО текущего пользователя, или статус гостя.
Кнопка "войти"/"выйти".
И возможно что-то ещё.

**Comment by agarb7** [comment]
Пока не виджет, а напрямую в коде. 
Нужно разобраться как его отрисовывать.

**Comment by tsyrya** [comment]
Не вопрос, подмогу.

**Comment by agarb7** [comment]
Ок, спасибо. Я пока персистентные объекты допилю до конца. Затем буду переводить регистрацию на них - и по ходу дела этим виджетом займусь.

**Comment by agarb7** [comment]
Это **пока** не нужно
