### ISSUE TITLE
Ошибка в заливочном скрипте

### ISSUE THREAD

**Issue by tsyrya** [agarb7/my.briop#72]
psql:../sql/schema/kurs.sql:71: ERROR:  syntax error at or near ""kontroliruyuschij_po_kursu""
LINE 1: create "kontroliruyuschij_po_kursu" (
               ^
psql:../sql/schema/kurs.sql:77: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:../sql/schema/kurs.sql:90: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:../sql/schema/kurs.sql:96: ERROR:  syntax error at or near ""kontroliruyuschij_po_podrazdelu_kursa""
LINE 1: create "kontroliruyuschij_po_podrazdelu_kursa" (
               ^
psql:../sql/schema/kurs.sql:71: ERROR:  syntax error at or near ""kontroliruyuschij_po_kursu""
LINE 1: create "kontroliruyuschij_po_kursu" (
               ^
psql:../sql/schema/kurs.sql:77: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:../sql/schema/kurs.sql:90: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:../sql/schema/kurs.sql:96: ERROR:  syntax error at or near ""kontroliruyuschij_po_podrazdelu_kursa""
LINE 1: create "kontroliruyuschij_po_podrazdelu_kursa" (
               ^

**Comment by agarb7** [comment]
исправил
