### ISSUE TITLE
Авторизация для next.briop.ru

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#74]

**Comment by agarb7** [comment]
Уточнение задачи: 
* реализовать авторизацию (контроль доступа), желательно средствами yii2
* интегрировать её в имеющийся код в места помеченные Цыреном
* сгенерировать и выдать учебному отделу логины и пароли для теста функциональности
* развернуть код и базу на сервере next.briop.ru

**Comment by agarb7** [comment]
* реализовал контроль доступа без yii (т.к. на данном шаге нецелесообразно)
* интегрировал
* отправил логины на е-майл
* развернул
