### ISSUE TITLE
Пометить места для интеграции авторизации

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#75]
Мне бы очень помог список файлов в которых нужно произвести изменения, а также метки в них.
Метки, например такие:
\>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
чтобы было видно.

**Comment by tsyrya** [comment]
Я тут словами напишу и в коде метки сделаю. 
1. в файле FileWidget USER_ID заменить на пользователь id. Если хочешь можешь переделать, имею ввиду, id пользователя сделать параметром виджета
2. В файле KursController.php  в экшене list $fz_id присвоить идентификатор физлица, убрать присвоение из GET
3. В файле KursController.php  в экшене edit проверить является ли эта программа доступной текущему пользователю.
4. Подумать, как сделать, чтобы не авторизованного пользователя всегда кидало на вход
3.

**Comment by agarb7** [comment]
Всё поправил. Спасибо.
