### ISSUE TITLE
Почему аутентификация по Ф.И.О. это плохо

### ISSUE THREAD

**Issue by agarb7** [agarb7/my.briop#76]
Это, возможно, необоснованные претензии к этому методу аутентификации пользователя. Но не могу смириться, пока не закрою все свои вопросы и возражения с этим связанные. Хочу разобраться коллегиально. 

Итак, почему аутентификацию по Ф.И.О. нельзя использовать:
1. Потому что есть однофамильцы, т.е. по Ф.И.О. нельзя однозначно определить пользователя.

Ваше решение?

**Comment by tsyrya** [comment]
Ну проблема однофамильности решается, как мне кажется, ведь вероятность, что в одной организации, на одной должности с одним фио будут два человека крайне мала. Но зато вместо логина можно будет, просто найти себя в списке. Имею ввиду,что при авторизации  по ФИО, нужно чтобы он обязательно выбрал себя из списка, но если он ввёл ФИО полностью и пароль, то в БД ищем связку ФИО и пароль, где вероятность совпадения так же  мала. А по поводу личной информации, место работы и должность не такой уж и секрет, как мне кажется. Поэтому я за такую авторизацию. Ваши аргументы?

**Comment by agarb7** [comment]
На одной должности с одним фио будут два человека, когда один и тот же человек зарегистрируется дважды (трижды...) из-за забывчивости или других проблем.
В эпоху законов о защите личной информации публичное раскрытие места работы немного настораживает. Более того просто информация о том, что человек зарегистрирован у нас в системе, вероятно тоже является личной.
Я считаю вариант показывать в списке "Фамилия Имя Отчество (login)" лучшим чем показывать место работы.
Но всё же самым лучшим считаю вариант, где авторизация проходит по логину или е-майлу. А в случае, если забыт логин присылать напоминание на е-майл по вводу Ф.И.О.
