### ISSUE TITLE
Проблема активация на my.briop.ru

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#78]
Санжижапова Цыренханда Санжиевна, внесла данные в форму регистрации. Пришло письмо на почту и при переходе по ссылке система выдает ошибку: произошла ошибка активации обратитесь к администратору сайта.

**Comment by svarkh** [comment]
Якушевич Галина Иннокентевна
не подходит пара логин пароль
похоже что она насоздавала кучу регистрационных данных

**Comment by agarb7** [comment]
Якушевич Г.И. - в системе только один пользователь. Подробности отправил почтой.

**Comment by agarb7** [comment]
Санжижапова Цыренханда Санжиевна - в БД запись активирована.

**Comment by svarkh** [comment]
зато есть через букву я маленькая


Вторник, 31 марта 2015, 21:05 -07:00 от agarb7 <notifications@github.com>:
>Якушевич Г.И. - в системе только один пользователь. Подробности отправил почтой.
>—
>Reply to this email directly or  view it on GitHub .


-- 
С уважением, Архипов Сергей Валерьевич
