### ISSUE TITLE
обновить список сотрудников и подразделений на next.briop.ru

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#79]
Неполный список преподавателей БРИОП, не внесены специалисты, АУП. Как добавить приглашенных преподавателей или это будет редактироваться в расписании

**Comment by agarb7** [comment]
Сотрудники из числа АУП были внесён ранее, но только без отношения к структурному подразделению. Сейчас только изменено это отношение (117e2c1c2e9efbbe9d6bdf6b91a180262ed8b330) в соответствии с https://drive.google.com/open?id=1rCItoPsreWTUSwHx0_0_De4Eb8suC3rOCC-fGj1Q_TQ&authuser=0, но там сотрудники всё те же.

**Comment by agarb7** [comment]
Приглашенные преподаватели к моменту редактирования программы курса уже есть среди пользователей системы?

**Comment by svarkh** [comment]
совмещение должностей
