### ISSUE TITLE
Программа курса. Вариативная часть - учет часов. 

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#81]
Допускается введение разного количества часов в блоках тем вариатива. Счет по первому блоку. Если не совпадает может всплывающее окно - количество часов в блоках тем не совпадает. Также по видам занятий в вариативе в сумме должно совпадать - не проверяет.
см. http://next.briop.ru/site/vhod проверка редактора курсов на примере программы Тармаевой Е.Р."Реализация системно-деятельностного подхода на уроках химии в соответствии с требованиями ФГОС ОО" 

логин tarmaevaer
пароль q_8k

**Comment by tsyrya** [comment]
Вроде сделал
