### ISSUE TITLE
Программа курса. Наименования разделов.

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#82]
В PI, PII, PIII выбор образовательной/управленческой деятельности добавить.

**Comment by agarb7** [comment]
Как я понимаю, это нужно сохранять в БД. Мне нужны подробности, чтобы наиболее адекватно относительно предметной области добавить атрибут в схему.
Это характеристика раздела, подраздела, темы или слушателя?

**Comment by tsyrya** [comment]
не, не будем это в базе хранить. По сути дела это те же PI,PII,PIII просто там одно слова различно. Сейчас в коде же названи яразделов определяем, там просто для поределенного вида курсов их по-другому назовем.

**Comment by svarkh** [comment]
В названиях раздела убрать PI, PII, PIII

**Comment by svarkh** [comment]
Решили делать выбор образовательной/управленческой деятельности. Думаю это не последний вариант пусть будет справочник.

**Comment by tsyrya** [comment]
Убрал названия PI и т.д. Со справочником разделов придется попотеть. Не понятно тогда как это должно выглядеть. Я думал они статичны, а на самом деле их вроде как тоже добавлять нужно. Мне немного пока не понятно. как это должно быть реализовано.

**Comment by svarkh** [comment]
Сейчас сделать так. В БД табличку справочник подразделов. На форме выпадающий список причем по умолчанию с текущими вариантами названия разделов.
В дальнейшем в кабинете у сотрудника УО сделаем функционал ведения справочников.

**Comment by agarb7** [comment]
Самый очевидный и болезненный вариант: сделать раздел сущностью, среди прочих атрибутов которой будет "образовательной/управленческой", который будет браться из справочника

**Comment by agarb7** [comment]
Реорганизовал БД: новая сущность в иерархии программы курса - раздел.
Справочник названий для разделов:
* Нормативно-правовые основы образовательной деятельности,
* Нормативно-правовые основы управленческой деятельности,
* Психолого-педагогические основы образовательной деятельности,
* Психолого-педагогические основы управленческой деятельности,
* Предметно-методические основы образовательной деятельности,
* Предметно-методические основы управленческой деятельности,
* Вариативная составляющая.
