### ISSUE TITLE
Письменное обращение в БРИОП

### ISSUE THREAD

**Issue by tsyrya** [agarb7/my.briop#9]
В ТЗ увидел, что должно прикладываться письменное обращение в БРИОП. Мне кажется в базе нужно где-то отобразить (имя файла где-то хранить). Как думаете?

**Comment by agarb7** [comment]
"4.3.4.1. Должность руководитель.Группа «Руководитель образовательного учреждения».
4.3.4.1.1. Проверка уникальности.
4.3.4.1.1.1. При положительной проверке – группа «Руководитель образовательного учреждения».
4.3.4.1.1.2. Письменное обращение в БРИОП."

Мне видется так. Плюс от хранения файла:
+ Информативность: сразу видно на каком основании
+ Удобство: если необходимо посмотреть заявление, не нужно лезть в бумажную картотеку
Минусы:
- Морока: их кому-то нужно сканировать и добавлять в систему
- Дополнительные мегабайты данных на сервере
- Нарушение единообразия рабочего процесса: я думаю, в работе организации будут появляться дополнительные внешние бумажные документы, тогда нужно их тоже сканировать и заливать; иначе: что делает это заявление особенным?

Я предлагаю хранить в базе только входящий номер заявления. А при редкой необходимости ознакомится с заявлением подробно, работнику придётся искать в бумажной картотеке. Как считаете?

**Comment by tsyrya** [comment]
Я понял, что его при регистрации в личном кабинете нужно приложить. Поэтому у меня возник вопрос куда его складывать. Но я не совсем понял, что за письменное обращение.

**Comment by agarb7** [comment]
Я понимаю так. Например, директор школы, чтобы отслеживать переподготовку учителей школы, регистрируется в системе как руководитель. Но чтобы посторонний человек не мог отслеживать кого угодно, он должен как-то верифицироваться. Поэтому если хочет отслеживать подчинённых - пусть несёт письмо в БРИОП.

**Comment by svarkh** [comment]
Здесь для руководителей разошлем письма с указанием, что они уже могут зайти через такие то логины и нужно заполнить актуальный mail. При смене руководства или каких-то других обстоятельствах  возможны письменные обращения на имя администрации

**Comment by svarkh** [comment]
думать о прикреплениях сканов в системе не нужно. Есть мыло пусть пишут туда.
