### ISSUE TITLE
Как запустить скрипт создания пользователей=)?

### ISSUE THREAD

**Issue by tsyrya** [agarb7/my.briop#90]
я пробовал вот так
http://www.next.briop/data/sozdatpolzovatelejrukovoditelyamkursov

**Comment by agarb7** [comment]
скрипт, по идее, консольный, хотя можно и через http.
Попробуй так:
http://www.next.briop/data/sozdat-polzovatelej-rukovoditelyam-kursov
по умолчанию в yii2 кэмэл-капс конвертируется в ловер слова разделённые дефисом.
(у меня так сработало, только домен другой)

**Comment by tsyrya** [comment]
Ок, чет я запарился=)
