### ISSUE TITLE
Программа курса. Нумерация тем, блоков разделов

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#92]
Нумерация тем идет по разному для {УП, КУГ} и содержания.
см http://next.briop.ru/kurs/edit?id=72

**Comment by svarkh** [comment]
Делаем нумерацию содержания так же как и в куге и учебном плане т.е. если нет блока тем в содержании, то в третьем и четвертом разделах первый индекс на 1 меньше чем сейчас

**Comment by tsyrya** [comment]
Переделал
