### ISSUE TITLE
Программа курса. Итоговая аттестация

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#95]
Не отображается форма контроля.

**Comment by agarb7** [comment]
Это та ошибка?
![snapshot2](https://cloud.githubusercontent.com/assets/8955838/7157897/229b078c-e39e-11e4-9c7c-774893625c12.png)

**Comment by svarkh** [comment]
Здесь не видно. Если сохранить и нажать f5, то сформируется КУГ и там в столбце должна появится запись о форме контроля. Так работает весть промежуточный контроль.
