### ISSUE TITLE
Программа курса. Курсы ПК.

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#97]
Есть курсы ПК по 24 часа и меньше. Для них блок тем и тема это одна тема в 2 часа.
УО ставит вопрос о возможности привязки тем к разделам на прямую.
#### Вариант 1.
Добавили раздел. Добавили тему или блок тем. В блоке добавили тему.
* [+] удобно им
* [-] нарушается структура иерархий:
    * бд
    * нумерация содержания
    * вывод в УП: раздел может остаться пустым
    * ?
* ?

#### Вариант 2. 
Добавили раздел. Добавили тему т.е. блоки тем для ПК не предусматривать.
* [+] относительно удобно им
* [-] бд
   * отдельные таблицы под курсы ПК
   * ?
* ?

**Comment by agarb7** [comment]
Что если сейчас оставить как есть и попросить их дублировать название темы в блоке тем. Далее, в процессе полного перехода на паттерн Репозиторий (исключения прямых обращений к БД), исправить на наилучший вариант и конвертнуть данные. - Всё равно рефакторить.

**Comment by tsyrya** [comment]
Я считаю тут нам нужно занять жесткую позицию. Почему курс должен по структуре отличаться, мне не понятно. Пусть сделают один блок тем, если очень не охота придумывать несколько. Потом нам везде придется костыли тыкать, ради этих курсов. Как говорится бардак не автоматизируется=) Давайте как-то переубедим их. Я чувствую, эти курсы могут стать камнем в огороде, где-то еще что-то вылезет, снова будет изощрятся и придумывать как базу пилить. Тем более в ТЗ не было прописано.

**Comment by svarkh** [comment]
Сегодня провели совещание на эту тему.
Предложил оставить все как есть.
Т.е. если в блоке одна тема, то пусть названия блока и темы совпадут. Тогда в УП автоматом вынесем блок и раздел не будет пустым. Этот аргумент их убедил (надеюсь). Каково было мое удивление когда я увидел реально подписанные планы состоящие только из названий разделов! Это пипец! Такого я не ожидал если честно...
Получается, что УП это пустышка, а КУГ это УП, при этом сам КУГ даже не намекает на график (об этом ранее я им тоже говорил). Возникает (он вобщем то и был) новый вопрос как из КУГ сделать крафик. Предложил такую схему: при добавлении темы нужно будет выбрать номер недели (1 неделя, 2 неделя и т.д.). В КУГе  отображать неделю в отдельном столбце например справа. Возможно форма КУГа приблизится к вузовскому графику учебного процесса (правда для курса в 9 дней он будет выглядеть нелепо). В случае если они все это примут, то будет тема нового issue.
