### ISSUE TITLE
Нужен доступ к списку записанных на курсы из my.briop

### ISSUE THREAD

**Issue by svarkh** [agarb7/my.briop#99]
Нужен доступ к списку записанных на курсы из my.briop для руководителей курсов.
Поля что есть в my.briop но в одной таблице (чтоб не разворачивать) и с выгрузкой в exel. Логичнее делать все в next.briop. Ведь объединения все еще нет!

**Comment by agarb7** [comment]
Мне нужно ещё пару дней для реализации базового функционала my.briop. К понедельнику первая версия объединения будет готова. Из проблем которые в ней, возможно, будут:
* Каптча (yii есть для этого стандартный функционал - нужно разобраться)
* E-mail подтверждение и отправка (нужно поразбираться в yii-шных фасадах для этого)
* Не очень удобный выбор адреса и обр.организаций (буду делать в последнюю очередь)
Милстоун по переходу истёк только сегодня: простите мне задержку в 3 дня)) - ведь мне не просто нужно на yii перевести, а качественно перелопатить проект.

После понедельника можно будет реализовывать этот функционал на этой новой версии в next.briop. А по закрытию изъянов первой версии (ещё пару дней) - в паблик продакшн.

**Comment by agarb7** [comment]
Друзья! Простите но мне нужно ещё немного времени: нужно сделать хорошо без костылей.

**Comment by tsyrya** [comment]
Я контроллер под это дело готовлю, когда будет готова переливка из абзы в базу. Я опубликую его.

**Comment by agarb7** [comment]
Эх. Ну тогда сегодня запилю конвертер, как экшен в некст-бриопе.
